language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
env:
  - ISOLCSS_ALLOW_RE=1 REGEX_VERSION=
  - REGEX_VERSION=0.1.20121120
install:
  - '[ -z "$REGEX_VERSION" ] || pip install -q regex==$REGEX_VERSION --use-mirrors'
script: python isolcss/tests.py
